PublicURL: http://127.0.0.1:8082
ListenAddr: :8080
RestLogLevel: info

IrodsHost: irods-provider
IrodsPort: 1247
IrodsZone: tempZone
IrodsAdminUser: rods
IrodsAdminPassword: rods
IrodsAdminPasswordFile:
IrodsAdminLoginType: native
IrodsAuthScheme: native
IrodsNegotiationPolicy: CS_NEG_DONT_CARE
IrodsSSLConfig:
  CACertificateFile:
  CACertificatePath:
  EncryptionKeySize: 32
  EncryptionAlgorithm: AES-256-CBC
  EncryptionSaltSize: 8
  EncryptionNumHashRounds: 16
  VerifyServer: hostname
  DHParamsFile:
  ServerName:
IrodsDefaultResource: providerResc

S3ApiSupported: false
S3BucketMappingFile:
S3UserMappingFile:

ReplicaTrimMinCopies: 1
ReplicaTrimMinAgeMinutes: 0
TestResource1: providerResc
TestResource2: providerResc

OidcUrl: https://keycloak:8443
OidcClientId: irods-go-rest
OidcClientSecret: change-me
OidcClientSecretFile:
OidcInsecureSkipVerify: true
OidcRealm: irods
OidcScope: openid profile email
