CREATE USER irods WITH PASSWORD 'testpassword';
CREATE DATABASE "ICAT" OWNER irods;
GRANT ALL PRIVILEGES ON DATABASE "ICAT" TO irods;

\connect "ICAT"
ALTER SCHEMA public OWNER TO irods;
GRANT ALL ON SCHEMA public TO irods;

\connect postgres
CREATE DATABASE "KEYCLOAK" OWNER irods;
GRANT ALL PRIVILEGES ON DATABASE "KEYCLOAK" TO irods;

\connect "KEYCLOAK"
ALTER SCHEMA public OWNER TO irods;
GRANT ALL ON SCHEMA public TO irods;
