#!/usr/bin/env bash
set -euo pipefail

: "${KEYCLOAK_DB_NAME:=KEYCLOAK}"
: "${KEYCLOAK_DB_USER:=keycloak}"
: "${KEYCLOAK_DB_PASSWORD:=keycloak}"

psql --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE USER "$KEYCLOAK_DB_USER" WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
CREATE DATABASE "$KEYCLOAK_DB_NAME" OWNER "$KEYCLOAK_DB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB_NAME" TO "$KEYCLOAK_DB_USER";
EOSQL

psql --username "$POSTGRES_USER" --dbname "$KEYCLOAK_DB_NAME" <<EOSQL
ALTER SCHEMA public OWNER TO "$KEYCLOAK_DB_USER";
GRANT ALL ON SCHEMA public TO "$KEYCLOAK_DB_USER";
EOSQL
